# samconfig.toml — Configuración de despliegue SAM
# Stack: pos-sam | Región: us-east-1

version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name          = "pos-sam"
region              = "us-east-1"
confirm_changeset   = true
capabilities        = "CAPABILITY_IAM"
resolve_s3          = true
s3_prefix           = "pos-sam"
parameter_overrides = ""
